---
title: "Comments response (SOFTX_2020_29)"
output: pdf_document
---

We first wish to thank the two reviewers for helpful comments. We have answered them all as below. The revised sections were marked by red text in the manuscript.


**Reviewer 1**
  
Overall well this is a well written paper written although there are a few typos in the text and it would benefit from a modest reordering of some of the text. Methodologically this is a sound piece of work. It does not contribute to the theory of GSA but the ability to introduce a phase-change is a useful advance compared to the eFAST routine coded in the R sensitivity package. The ability to work with models coded in GNU MCSim is particularly useful since there is no support for GSA within this software. The plots that can be seen in Figure 2 neatly demonstrate the advantage of taking replicates although for a highly parameterised and computationally expensive model this will come with a hefty overhead, particularly for models coded using deSolve. The paper over really skims over the capability of the pksensi package although it does provide a link to fuller guidance.

**Ans: We have edited the paper to address typos, as well as did some re-ordering of the text, as described below.  Due to word count limits, we are unable to provide additional details in the text as to the capability of the package, though as the reviewer notes, links to fuller guidance are included.**

I have only a few minor comments.

  1. The workflow shown in figure 1 demonstrates what I would regard as best practice for development and calibration of a PBPK model. Uncertainty analysis in some form for the testing, debugging and assessment of the quantitative behaviour of a model over the bounds of the input parameters is an essential prerequisite to sensitivity analysis. However, whilst this is briefly covered in the text (beginning on line 137) the authors don’t specify how the results from uncertainty analysis might be used to refine parameter ranges. Furthermore, there is no mention of uncertainty analysis in the 5 step routine in the illustrative examples section.  
  **Ans: The basic idea of uncertainty analysis in pksensi is to examine if the data from the in-vivo experiment can be located in the range of model simulation output. If not, the modeler should examine all possible reasons that cause the problem (e.g., too narrow parameter range or incomplete model structure). However, detailing the parameter adjustment process after uncertainty analysis is out of the scope of this package, and additional explanation can exceed the word limit in the softwareX. We do, though, have an example of uncertainty analysis for the acetaminophen-PBPK model that was provided in the pksensi website (https://nanhung.netlify.app/pksensi/articles/pbpk_apap.html). Additionally, the step of uncertainty analysis had also been added to the examples section.**
  
  2. I suggest the authors review the ordering of the text so that it reflects the workflow of figure 1. At present the text on uncertainty analysis follows the text on sensitivity analysis.  
  **Ans: We revised and added the content from the sections "Uncertainty analysis" and "Sensitivity analysis" to reflect the workflow of figure 1.** 

  3. Paragraph starting on line 137. 'The uncertainty analysis is a crucial modelling process within SA ...' Uncertainty analysis is the study of uncertainty in model outputs that arises as a consequence of uncertainty on model inputs. Sensitivity analysis goes a step further in attributing the uncertainty in outputs to individual parameters or interactions between parameters. Uncertainty and sensitivity analysis are distinct but complimentary processes.  
  **Ans: We separate the uncertainty and sensitivity analysis into two subsections (2.4 & 2.5) for clarity.**

**Reviewer 2**
  
- Major Revision

  1. This article does not follow templates of this journal:
    - The words in abstract is about 222 words which is much larger than 100 words.
    - The words in main text is about 5578 words which is much larger than 3000 words.
    - Software metadata table is missing.  
  **Ans: After double-checking the Guide for Authors in SoftwareX web page (https://www.elsevier.com/journals/softwarex/2352-7110/guide-for-authors), we think that there is no word restriction for the abstract. Overall, we removed some context make the article more concise. The result from textcount (https://app.uio.no/ifi/texcount/online.php) shows that the words in the manuscript are under 3000 words as below. The software metadata table had been added in the manuscript as well.**

```
Word count
Words in text: 2839
Words in headers: 55
Words outside text (captions, etc.): 75
Number of headers: 18
Number of floats/tables/figures: 5
Number of math inlines: 14
Number of math displayed: 2
Subcounts:
  text+headers+captions (#headers/#floats/#inlines/#displayed)
  222+15+0 (2/0/0/0) _top_
  0+2+0 (1/0/0/0) Section: Required Metadata
  0+3+3 (1/1/0/0) Section: Current code version
  598+3+0 (1/0/0/0) Section: Motivation and significance
  72+2+0 (1/0/0/0) Section: Software description
  39+1+0 (1/0/0/0) Subsection: Installation
  401+3+0 (1/0/11/2) Subsection: Parameter matrix generation
  149+1+0 (1/0/0/0) Subsection: Modeling
  175+2+0 (1/0/0/0) Subsection: Uncertainty analysis
  122+2+0 (1/0/0/0) Subsection: Sensitivity analysis
  405+2+0 (1/0/3/0) Section: Illustrative Examples
  527+3+0 (1/0/0/0) Section: Impact and conclusions
  26+3+0 (1/0/0/0) Section: Conflict of Interest
  82+1+0 (1/0/0/0) Section: Acknowledgements
  0+4+0 (1/0/0/0) Section: Appendix A. Example code
  21+4+69 (1/3/0/0) Section: CRediT authorship contribution statement
  0+4+3 (1/1/0/0) Section: Current executable software version
```
  
  2. Proprietary names such as R package names would be shown better in Gothic or bold font. 'pksensi' is in bold but other package names such as 'sensitivity' are not in bold, which is a little confusing in reading the text.  
  **Ans: We revised the article and used bold font for all mentioned R packages.**
  
- Minor Comments

  1. Line 187-188: Statements are hard to understand. It needs correction at 'to further used,' and 'thwe' in the following text: "The corresponding ranges have to define in a list object, a generic vector to further used in the analysis. After the definition, thwe users can use rfast99() to create parameter matrix."  
  **Ans: We revised the description as "The next step is to identify the model parameters that will be examed in global SA and create the parameter matrix. After parameter selection, we have to assign each parameter a probability distribution over which to evaluate, such as a uniform distribution with specified min and max. The users then can use \textit{\textbf{rfast99()}} with the above assignments (e.g., parameter names, sample number, parameter distribution, and its corresponding properties) to create the parameter matrix."**
